/** \file
 *  This C source file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : /home/aymane/COURS/Projet antlr/s.g
 *     -                            On : 2011-05-29 12:39:54
 *     -                 for the lexer : sLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "sLexer.h"
/* ----------------------------------------- */


/** String literals used by sLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x3C, 0x44, 0x6F, 0x63, 0x75, 0x6D, 0x65, 0x6E, 0x74, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x3C, 0x6E, 0x61, 0x6D, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x3C, 0x2F, 0x6E, 0x61, 0x6D, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x3C, 0x2F, 0x44, 0x6F, 0x63, 0x75, 0x6D, 0x65, 0x6E, 0x74, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x3C, 0x2F, 0x6B, 0x6D, 0x6C, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x3C, 0x53, 0x74, 0x79, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x3C, 0x49, 0x63, 0x6F, 0x6E, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x3C, 0x73, 0x63, 0x61, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x3C, 0x2F, 0x73, 0x63, 0x61, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x3C, 0x49, 0x63, 0x6F, 0x6E, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x3C, 0x68, 0x72, 0x65, 0x66, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x3C, 0x2F, 0x68, 0x72, 0x65, 0x66, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x3C, 0x2F, 0x49, 0x63, 0x6F, 0x6E, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x3C, 0x2F, 0x49, 0x63, 0x6F, 0x6E, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x3C, 0x4C, 0x61, 0x62, 0x65, 0x6C, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_16[]  = { 0x3C, 0x63, 0x6F, 0x6C, 0x6F, 0x72, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_17[]  = { 0x3C, 0x2F, 0x63, 0x6F, 0x6C, 0x6F, 0x72, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_18[]  = { 0x3C, 0x2F, 0x4C, 0x61, 0x62, 0x65, 0x6C, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_19[]  = { 0x3C, 0x2F, 0x53, 0x74, 0x79, 0x6C, 0x65, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_20[]  = { 0x3C, 0x50, 0x6C, 0x61, 0x63, 0x65, 0x6D, 0x61, 0x72, 0x6B, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_21[]  = { 0x3C, 0x2F, 0x50, 0x6C, 0x61, 0x63, 0x65, 0x6D, 0x61, 0x72, 0x6B, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_22[]  = { 0x3C, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6F, 0x6E, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_23[]  = { 0x3C, 0x21, 0x5B, 0x43, 0x44, 0x41, 0x54, 0x41, 0x5B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_24[]  = { 0x3E, 0x70, 0x6F, 0x70, 0x75, 0x6C, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x3A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_25[]  = { 0x3C, 0x62, 0x72, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_26[]  = { 0x3C, 0x61,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_27[]  = { 0x3C, 0x2F, 0x61, 0x3E, 0x3C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_28[]  = { 0x3C, 0x2F, 0x66, 0x6F, 0x6E, 0x74, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_29[]  = { 0x5D, 0x5D, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_30[]  = { 0x3C, 0x2F, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6F, 0x6E, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_31[]  = { 0x3C, 0x73, 0x74, 0x79, 0x6C, 0x65, 0x55, 0x72, 0x6C, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_32[]  = { 0x3C, 0x2F, 0x73, 0x74, 0x79, 0x6C, 0x65, 0x55, 0x72, 0x6C, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_33[]  = { 0x3C, 0x50, 0x6F, 0x69, 0x6E, 0x74, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_34[]  = { 0x3C, 0x2F, 0x50, 0x6F, 0x69, 0x6E, 0x74, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_35[]  = { 0x3C, 0x63, 0x6F, 0x6F, 0x72, 0x64, 0x69, 0x6E, 0x61, 0x74, 0x65, 0x73, 0x3E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_36[]  = { 0x3C, 0x2F, 0x63, 0x6F, 0x6F, 0x72, 0x64, 0x69, 0x6E, 0x61, 0x74, 0x65, 0x73, 0x3E,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   psLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  psLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->psLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->psLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__8    (psLexer ctx);
static ANTLR3_INLINE  void	mT__9    (psLexer ctx);
static ANTLR3_INLINE  void	mT__10    (psLexer ctx);
static ANTLR3_INLINE  void	mT__11    (psLexer ctx);
static ANTLR3_INLINE  void	mT__12    (psLexer ctx);
static ANTLR3_INLINE  void	mT__13    (psLexer ctx);
static ANTLR3_INLINE  void	mT__14    (psLexer ctx);
static ANTLR3_INLINE  void	mT__15    (psLexer ctx);
static ANTLR3_INLINE  void	mT__16    (psLexer ctx);
static ANTLR3_INLINE  void	mT__17    (psLexer ctx);
static ANTLR3_INLINE  void	mT__18    (psLexer ctx);
static ANTLR3_INLINE  void	mT__19    (psLexer ctx);
static ANTLR3_INLINE  void	mT__20    (psLexer ctx);
static ANTLR3_INLINE  void	mT__21    (psLexer ctx);
static ANTLR3_INLINE  void	mT__22    (psLexer ctx);
static ANTLR3_INLINE  void	mT__23    (psLexer ctx);
static ANTLR3_INLINE  void	mT__24    (psLexer ctx);
static ANTLR3_INLINE  void	mT__25    (psLexer ctx);
static ANTLR3_INLINE  void	mT__26    (psLexer ctx);
static ANTLR3_INLINE  void	mT__27    (psLexer ctx);
static ANTLR3_INLINE  void	mT__28    (psLexer ctx);
static ANTLR3_INLINE  void	mT__29    (psLexer ctx);
static ANTLR3_INLINE  void	mT__30    (psLexer ctx);
static ANTLR3_INLINE  void	mT__31    (psLexer ctx);
static ANTLR3_INLINE  void	mT__32    (psLexer ctx);
static ANTLR3_INLINE  void	mT__33    (psLexer ctx);
static ANTLR3_INLINE  void	mT__34    (psLexer ctx);
static ANTLR3_INLINE  void	mT__35    (psLexer ctx);
static ANTLR3_INLINE  void	mT__36    (psLexer ctx);
static ANTLR3_INLINE  void	mT__37    (psLexer ctx);
static ANTLR3_INLINE  void	mT__38    (psLexer ctx);
static ANTLR3_INLINE  void	mT__39    (psLexer ctx);
static ANTLR3_INLINE  void	mT__40    (psLexer ctx);
static ANTLR3_INLINE  void	mT__41    (psLexer ctx);
static ANTLR3_INLINE  void	mT__42    (psLexer ctx);
static ANTLR3_INLINE  void	mT__43    (psLexer ctx);
static ANTLR3_INLINE  void	mT__44    (psLexer ctx);
static ANTLR3_INLINE  void	mT__45    (psLexer ctx);
static ANTLR3_INLINE  void	mCOO    (psLexer ctx);
static ANTLR3_INLINE  void	mNOM    (psLexer ctx);
static ANTLR3_INLINE  void	mALPHA    (psLexer ctx);
static ANTLR3_INLINE  void	mWS    (psLexer ctx);
static ANTLR3_INLINE  void	mTokens    (psLexer ctx);
static void	sLexerFree(psLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
sLexerFree  (psLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

static void
sLexerReset (psLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/aymane/COURS/Projet antlr/s.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called sLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success psLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API psLexer sLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return sLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called sLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success psLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API psLexer sLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    psLexer ctx; // Context structure we will build and return

    ctx = (psLexer) ANTLR3_CALLOC(1, sizeof(sLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in sLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our sLexer interface
     */
    ctx->mT__8	= mT__8;
    ctx->mT__9	= mT__9;
    ctx->mT__10	= mT__10;
    ctx->mT__11	= mT__11;
    ctx->mT__12	= mT__12;
    ctx->mT__13	= mT__13;
    ctx->mT__14	= mT__14;
    ctx->mT__15	= mT__15;
    ctx->mT__16	= mT__16;
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mT__26	= mT__26;
    ctx->mT__27	= mT__27;
    ctx->mT__28	= mT__28;
    ctx->mT__29	= mT__29;
    ctx->mT__30	= mT__30;
    ctx->mT__31	= mT__31;
    ctx->mT__32	= mT__32;
    ctx->mT__33	= mT__33;
    ctx->mT__34	= mT__34;
    ctx->mT__35	= mT__35;
    ctx->mT__36	= mT__36;
    ctx->mT__37	= mT__37;
    ctx->mT__38	= mT__38;
    ctx->mT__39	= mT__39;
    ctx->mT__40	= mT__40;
    ctx->mT__41	= mT__41;
    ctx->mT__42	= mT__42;
    ctx->mT__43	= mT__43;
    ctx->mT__44	= mT__44;
    ctx->mT__45	= mT__45;
    ctx->mCOO	= mCOO;
    ctx->mNOM	= mNOM;
    ctx->mALPHA	= mALPHA;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= sLexerFree;
    ctx->reset          = sLexerReset;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__8 | T__9 | T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | COO | NOM | ALPHA | WS );
 */
static const ANTLR3_INT32 dfa5_eot[69] =
    {
	8, 26, 28, 9, 8, 30, 30, 8, -1, -1, 8, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa5_eof[69] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa5_min[69] =
    {
	9, 33, 112, 93, 32, 32, 32, 32, -1, -1, 32, -1, -1, -1, 68, -1, 99, 99, 
	-1, -1, 111, 108, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, -1, 99, -1, 
	99, 111, -1, -1, 108, -1, -1, -1, 111, -1, -1, 108, -1, -1, -1, -1, -1, 
	111, 108, -1, -1, 110, -1, -1, 110, -1, -1, 62, 62, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa5_max[69] =
    {
	246, 115, 112, 93, 246, 246, 246, 246, -1, -1, 246, -1, -1, -1, 115, -1, 
	99, 116, -1, -1, 111, 111, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, 
	-1, 116, -1, 99, 111, -1, -1, 111, -1, -1, -1, 111, -1, -1, 111, -1, -1, 
	-1, -1, -1, 111, 111, -1, -1, 110, -1, -1, 110, -1, -1, 83, 83, -1, -1, 
	-1, -1
    };
static const ANTLR3_INT32 dfa5_accept[69] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, 40, 41, -1, 42, 3, 4, -1, 8, -1, -1, 13, 
	17, -1, -1, 24, 25, 27, 28, 1, 26, 2, -1, 39, 5, 6, 7, -1, 14, -1, -1, 
	20, 21, -1, 29, 30, 32, -1, 10, 33, -1, 22, 35, 31, 11, 34, -1, -1, 23, 
	36, -1, 18, 37, -1, 19, 38, -1, -1, 9, 12, 15, 16
    };
static const ANTLR3_INT32 dfa5_special[69] =
    {	
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa5_T_empty	    NULL

static const ANTLR3_INT32 dfa5_T0[] =
    {
	29
    };static const ANTLR3_INT32 dfa5_T1[] =
    {
	50
    };static const ANTLR3_INT32 dfa5_T2[] =
    {
	10, 9, 9, 9, -1, -1, 9, 10, -1, -1, -1, -1, 9, 10, 6, 9, 5, 5, 5, 5, 5, 
	5, 5, 5, 5, 5, 9, 9, -1, 9, -1, 9, -1, 10, 10, 10, 10, 10, 10, 10, 10, 
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
	-1, -1, 9, -1, -1, -1, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, 10, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 10, 10, -1, 
	10, -1, -1, 10, -1, -1, -1, -1, -1, 10, -1, 10
    };static const ANTLR3_INT32 dfa5_T3[] =
    {
	10, 9, 9, 9, -1, -1, 9, 10, -1, -1, -1, -1, 9, 10, 9, 9, 10, 10, 10, 10, 
	10, 10, 10, 10, 10, 10, 9, 9, -1, 9, -1, 9, -1, 10, 10, 10, 10, 10, 10, 
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
	10, 10, -1, -1, 9, -1, -1, -1, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, 10, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 10, 
	10, -1, 10, -1, -1, 10, -1, -1, -1, -1, -1, 10, -1, 10
    };static const ANTLR3_INT32 dfa5_T4[] =
    {
	55, -1, -1, 56
    };static const ANTLR3_INT32 dfa5_T5[] =
    {
	10, 9, 9, 9, -1, -1, 9, 10, -1, -1, -1, -1, 9, 10, 6, 9, 5, 5, 5, 5, 5, 
	5, 5, 5, 5, 5, 9, 9, -1, 9, -1, 9, -1, 10, 10, 10, 10, 10, 10, 10, 10, 
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
	-1, -1, 9, -1, -1, -1, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, 10, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, 8, -1, 8, -1, -1, -1, -1, 8, 10, 10, 8, 10, 
	-1, -1, 10, -1, -1, -1, -1, -1, 10, -1, 10
    };static const ANTLR3_INT32 dfa5_T6[] =
    {
	27
    };static const ANTLR3_INT32 dfa5_T7[] =
    {
	9, 9, 9, 9, -1, -1, 9, 9, -1, -1, -1, -1, 9, 9, 6, 9, 6, 6, 6, 6, 6, 6, 
	6, 6, 6, 6, 9, 9, -1, 9, -1, 9, -1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
	9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, -1, -1, 9, -1, -1, -1, 9, 9, 
	9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, 9, -1, -1, -1, -1, 9, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	9, 9, -1, 9, -1, -1, 9, -1, -1, -1, -1, -1, 9, -1, 9
    };static const ANTLR3_INT32 dfa5_T8[] =
    {
	61, -1, -1, 62
    };static const ANTLR3_INT32 dfa5_T9[] =
    {
	23, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 14, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 12, 
	-1, -1, -1, -1, 16, -1, -1, 19, -1, -1, -1, 21, -1, -1, 15, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 25, 24, 20, 22, -1, -1, -1, 18, 
	-1, -1, -1, -1, -1, 13, -1, -1, -1, -1, 17
    };static const ANTLR3_INT32 dfa5_T10[] =
    {
	48, -1, -1, 49
    };static const ANTLR3_INT32 dfa5_T11[] =
    {
	54
    };static const ANTLR3_INT32 dfa5_T12[] =
    {
	58, -1, -1, 59
    };static const ANTLR3_INT32 dfa5_T13[] =
    {
	47
    };static const ANTLR3_INT32 dfa5_T14[] =
    {
	45, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 46
    };static const ANTLR3_INT32 dfa5_T15[] =
    {
	67, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, 68
    };static const ANTLR3_INT32 dfa5_T16[] =
    {
	32, -1, -1, -1, -1, 36, -1, -1, 38, -1, -1, -1, 40, -1, -1, 39, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 41, -1, 37, 43, -1, 42, -1, 
	35, -1, -1, 33, -1, -1, 31, -1, -1, -1, -1, 34
    };static const ANTLR3_INT32 dfa5_T17[] =
    {
	64
    };static const ANTLR3_INT32 dfa5_T18[] =
    {
	60
    };static const ANTLR3_INT32 dfa5_T19[] =
    {
	53
    };static const ANTLR3_INT32 dfa5_T20[] =
    {
	51, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 52
    };static const ANTLR3_INT32 dfa5_T21[] =
    {
	11, 11, -1, -1, 11, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 7, 9, 9, 9, -1, -1, 9, 10, -1, -1, -1, -1, 9, 4, 6, 
	9, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 9, 9, 1, 9, 2, 9, -1, 10, 10, 10, 10, 
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
	10, 10, 10, 10, -1, -1, 3, -1, -1, -1, 10, 10, 10, 10, 10, 10, 10, 10, 
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, 10, -1, -1, -1, -1, 10, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, 10, 10, -1, 10, -1, -1, 10, -1, -1, -1, -1, -1, 10, -1, 10
    };static const ANTLR3_INT32 dfa5_T22[] =
    {
	44
    };static const ANTLR3_INT32 dfa5_T23[] =
    {
	57
    };static const ANTLR3_INT32 dfa5_T24[] =
    {
	63
    };static const ANTLR3_INT32 dfa5_T25[] =
    {
	66, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, 65
    };

/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa5_transitions[] =
{
    dfa5_T21, dfa5_T9, dfa5_T6, dfa5_T0, dfa5_T2, dfa5_T5, dfa5_T7, dfa5_T3, 
    dfa5_T_empty, dfa5_T_empty, dfa5_T3, dfa5_T_empty, dfa5_T_empty, dfa5_T_empty, 
    dfa5_T16, dfa5_T_empty, dfa5_T22, dfa5_T14, dfa5_T_empty, dfa5_T_empty, 
    dfa5_T13, dfa5_T10, dfa5_T_empty, dfa5_T_empty, dfa5_T_empty, dfa5_T_empty, 
    dfa5_T_empty, dfa5_T_empty, dfa5_T_empty, dfa5_T1, dfa5_T_empty, dfa5_T_empty, 
    dfa5_T_empty, dfa5_T_empty, dfa5_T20, dfa5_T_empty, dfa5_T19, dfa5_T11, 
    dfa5_T_empty, dfa5_T_empty, dfa5_T4, dfa5_T_empty, dfa5_T_empty, dfa5_T_empty, 
    dfa5_T23, dfa5_T_empty, dfa5_T_empty, dfa5_T12, dfa5_T_empty, dfa5_T_empty, 
    dfa5_T_empty, dfa5_T_empty, dfa5_T_empty, dfa5_T18, dfa5_T8, dfa5_T_empty, 
    dfa5_T_empty, dfa5_T24, dfa5_T_empty, dfa5_T_empty, dfa5_T17, dfa5_T_empty, 
    dfa5_T_empty, dfa5_T25, dfa5_T15, dfa5_T_empty, dfa5_T_empty, dfa5_T_empty, 
    dfa5_T_empty	
};


/* Declare tracking structure for Cyclic DFA 5
 */
static
ANTLR3_CYCLIC_DFA cdfa5
    =	{
	    5,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__8 | T__9 | T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | COO | NOM | ALPHA | WS );",	
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/
	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa5_eot,	    /* EOT table			    */
	    dfa5_eof,	    /* EOF table			    */
	    dfa5_min,	    /* Minimum tokens for each state    */
	    dfa5_max,	    /* Maximum tokens for each state    */
	    dfa5_accept,	/* Accept table			    */
	    dfa5_special,	/* Special transition states	    */
	    dfa5_transitions	/* Table of transition tables	    */

	};	    
/* End of Cyclic DFA 5
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */ 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:6: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__8
 *
 * Looks to match the characters the constitute the token T__8
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__8(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__8;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:7:6: ( '<' )
    // /home/aymane/COURS/Projet antlr/s.g:7:8: '<'
    {
        MATCHC('<'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__8Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__8Ex; /* Prevent compiler warnings */
    ruleT__8Ex: ;

}
// $ANTLR end T__8

//   Comes from: 8:6: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__9
 *
 * Looks to match the characters the constitute the token T__9
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__9(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__9;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:8:6: ( '>' )
    // /home/aymane/COURS/Projet antlr/s.g:8:8: '>'
    {
        MATCHC('>'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__9Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__9Ex; /* Prevent compiler warnings */
    ruleT__9Ex: ;

}
// $ANTLR end T__9

//   Comes from: 9:7: ( '<Document>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__10
 *
 * Looks to match the characters the constitute the token T__10
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__10(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__10;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:9:7: ( '<Document>' )
    // /home/aymane/COURS/Projet antlr/s.g:9:9: '<Document>'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleT__10Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__10Ex; /* Prevent compiler warnings */
    ruleT__10Ex: ;

}
// $ANTLR end T__10

//   Comes from: 10:7: ( '<name>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__11
 *
 * Looks to match the characters the constitute the token T__11
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__11(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__11;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:10:7: ( '<name>' )
    // /home/aymane/COURS/Projet antlr/s.g:10:9: '<name>'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleT__11Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__11Ex; /* Prevent compiler warnings */
    ruleT__11Ex: ;

}
// $ANTLR end T__11

//   Comes from: 11:7: ( '</name>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__12
 *
 * Looks to match the characters the constitute the token T__12
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__12(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__12;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:11:7: ( '</name>' )
    // /home/aymane/COURS/Projet antlr/s.g:11:9: '</name>'
    {
        MATCHS(lit_3); 
        if  (HASEXCEPTION())
        {
            goto ruleT__12Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__12Ex; /* Prevent compiler warnings */
    ruleT__12Ex: ;

}
// $ANTLR end T__12

//   Comes from: 12:7: ( '</Document>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__13
 *
 * Looks to match the characters the constitute the token T__13
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__13(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__13;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:12:7: ( '</Document>' )
    // /home/aymane/COURS/Projet antlr/s.g:12:9: '</Document>'
    {
        MATCHS(lit_4); 
        if  (HASEXCEPTION())
        {
            goto ruleT__13Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__13Ex; /* Prevent compiler warnings */
    ruleT__13Ex: ;

}
// $ANTLR end T__13

//   Comes from: 13:7: ( '</kml>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__14
 *
 * Looks to match the characters the constitute the token T__14
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__14(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__14;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:13:7: ( '</kml>' )
    // /home/aymane/COURS/Projet antlr/s.g:13:9: '</kml>'
    {
        MATCHS(lit_5); 
        if  (HASEXCEPTION())
        {
            goto ruleT__14Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__14Ex; /* Prevent compiler warnings */
    ruleT__14Ex: ;

}
// $ANTLR end T__14

//   Comes from: 14:7: ( '<Style' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__15
 *
 * Looks to match the characters the constitute the token T__15
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__15(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__15;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:14:7: ( '<Style' )
    // /home/aymane/COURS/Projet antlr/s.g:14:9: '<Style'
    {
        MATCHS(lit_6); 
        if  (HASEXCEPTION())
        {
            goto ruleT__15Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__15Ex; /* Prevent compiler warnings */
    ruleT__15Ex: ;

}
// $ANTLR end T__15

//   Comes from: 15:7: ( '<IconStyle>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__16
 *
 * Looks to match the characters the constitute the token T__16
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__16(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__16;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:15:7: ( '<IconStyle>' )
    // /home/aymane/COURS/Projet antlr/s.g:15:9: '<IconStyle>'
    {
        MATCHS(lit_7); 
        if  (HASEXCEPTION())
        {
            goto ruleT__16Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__16Ex; /* Prevent compiler warnings */
    ruleT__16Ex: ;

}
// $ANTLR end T__16

//   Comes from: 16:7: ( '<scale>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:16:7: ( '<scale>' )
    // /home/aymane/COURS/Projet antlr/s.g:16:9: '<scale>'
    {
        MATCHS(lit_8); 
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 17:7: ( '</scale>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:17:7: ( '</scale>' )
    // /home/aymane/COURS/Projet antlr/s.g:17:9: '</scale>'
    {
        MATCHS(lit_9); 
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 18:7: ( '<Icon>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:18:7: ( '<Icon>' )
    // /home/aymane/COURS/Projet antlr/s.g:18:9: '<Icon>'
    {
        MATCHS(lit_10); 
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 19:7: ( '<href>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:19:7: ( '<href>' )
    // /home/aymane/COURS/Projet antlr/s.g:19:9: '<href>'
    {
        MATCHS(lit_11); 
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 20:7: ( '</href>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:20:7: ( '</href>' )
    // /home/aymane/COURS/Projet antlr/s.g:20:9: '</href>'
    {
        MATCHS(lit_12); 
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 21:7: ( '</Icon>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__22;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:21:7: ( '</Icon>' )
    // /home/aymane/COURS/Projet antlr/s.g:21:9: '</Icon>'
    {
        MATCHS(lit_13); 
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 22:7: ( '</IconStyle>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__23;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:22:7: ( '</IconStyle>' )
    // /home/aymane/COURS/Projet antlr/s.g:22:9: '</IconStyle>'
    {
        MATCHS(lit_14); 
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 23:7: ( '<LabelStyle>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:23:7: ( '<LabelStyle>' )
    // /home/aymane/COURS/Projet antlr/s.g:23:9: '<LabelStyle>'
    {
        MATCHS(lit_15); 
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 24:7: ( '<color>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:24:7: ( '<color>' )
    // /home/aymane/COURS/Projet antlr/s.g:24:9: '<color>'
    {
        MATCHS(lit_16); 
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 25:7: ( '</color>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__26
 *
 * Looks to match the characters the constitute the token T__26
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__26(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__26;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:25:7: ( '</color>' )
    // /home/aymane/COURS/Projet antlr/s.g:25:9: '</color>'
    {
        MATCHS(lit_17); 
        if  (HASEXCEPTION())
        {
            goto ruleT__26Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__26Ex; /* Prevent compiler warnings */
    ruleT__26Ex: ;

}
// $ANTLR end T__26

//   Comes from: 26:7: ( '</LabelStyle>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__27;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:26:7: ( '</LabelStyle>' )
    // /home/aymane/COURS/Projet antlr/s.g:26:9: '</LabelStyle>'
    {
        MATCHS(lit_18); 
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 27:7: ( '</Style>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__28
 *
 * Looks to match the characters the constitute the token T__28
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__28(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__28;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:27:7: ( '</Style>' )
    // /home/aymane/COURS/Projet antlr/s.g:27:9: '</Style>'
    {
        MATCHS(lit_19); 
        if  (HASEXCEPTION())
        {
            goto ruleT__28Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__28Ex; /* Prevent compiler warnings */
    ruleT__28Ex: ;

}
// $ANTLR end T__28

//   Comes from: 28:7: ( '<Placemark>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__29
 *
 * Looks to match the characters the constitute the token T__29
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__29(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__29;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:28:7: ( '<Placemark>' )
    // /home/aymane/COURS/Projet antlr/s.g:28:9: '<Placemark>'
    {
        MATCHS(lit_20); 
        if  (HASEXCEPTION())
        {
            goto ruleT__29Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__29Ex; /* Prevent compiler warnings */
    ruleT__29Ex: ;

}
// $ANTLR end T__29

//   Comes from: 29:7: ( '</Placemark>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__30;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:29:7: ( '</Placemark>' )
    // /home/aymane/COURS/Projet antlr/s.g:29:9: '</Placemark>'
    {
        MATCHS(lit_21); 
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 30:7: ( '<description>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__31;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:30:7: ( '<description>' )
    // /home/aymane/COURS/Projet antlr/s.g:30:9: '<description>'
    {
        MATCHS(lit_22); 
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 31:7: ( '<![CDATA[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__32
 *
 * Looks to match the characters the constitute the token T__32
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__32(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__32;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:31:7: ( '<![CDATA[' )
    // /home/aymane/COURS/Projet antlr/s.g:31:9: '<![CDATA['
    {
        MATCHS(lit_23); 
        if  (HASEXCEPTION())
        {
            goto ruleT__32Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__32Ex; /* Prevent compiler warnings */
    ruleT__32Ex: ;

}
// $ANTLR end T__32

//   Comes from: 32:7: ( '>population:' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__33
 *
 * Looks to match the characters the constitute the token T__33
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__33(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__33;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:32:7: ( '>population:' )
    // /home/aymane/COURS/Projet antlr/s.g:32:9: '>population:'
    {
        MATCHS(lit_24); 
        if  (HASEXCEPTION())
        {
            goto ruleT__33Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__33Ex; /* Prevent compiler warnings */
    ruleT__33Ex: ;

}
// $ANTLR end T__33

//   Comes from: 33:7: ( '<br>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__34
 *
 * Looks to match the characters the constitute the token T__34
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__34(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__34;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:33:7: ( '<br>' )
    // /home/aymane/COURS/Projet antlr/s.g:33:9: '<br>'
    {
        MATCHS(lit_25); 
        if  (HASEXCEPTION())
        {
            goto ruleT__34Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__34Ex; /* Prevent compiler warnings */
    ruleT__34Ex: ;

}
// $ANTLR end T__34

//   Comes from: 34:7: ( '<a' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__35
 *
 * Looks to match the characters the constitute the token T__35
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__35(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__35;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:34:7: ( '<a' )
    // /home/aymane/COURS/Projet antlr/s.g:34:9: '<a'
    {
        MATCHS(lit_26); 
        if  (HASEXCEPTION())
        {
            goto ruleT__35Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__35Ex; /* Prevent compiler warnings */
    ruleT__35Ex: ;

}
// $ANTLR end T__35

//   Comes from: 35:7: ( '</a><' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__36
 *
 * Looks to match the characters the constitute the token T__36
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__36(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__36;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:35:7: ( '</a><' )
    // /home/aymane/COURS/Projet antlr/s.g:35:9: '</a><'
    {
        MATCHS(lit_27); 
        if  (HASEXCEPTION())
        {
            goto ruleT__36Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__36Ex; /* Prevent compiler warnings */
    ruleT__36Ex: ;

}
// $ANTLR end T__36

//   Comes from: 36:7: ( '</font>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__37
 *
 * Looks to match the characters the constitute the token T__37
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__37(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__37;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:36:7: ( '</font>' )
    // /home/aymane/COURS/Projet antlr/s.g:36:9: '</font>'
    {
        MATCHS(lit_28); 
        if  (HASEXCEPTION())
        {
            goto ruleT__37Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__37Ex; /* Prevent compiler warnings */
    ruleT__37Ex: ;

}
// $ANTLR end T__37

//   Comes from: 37:7: ( ']]>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__38
 *
 * Looks to match the characters the constitute the token T__38
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__38(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__38;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:37:7: ( ']]>' )
    // /home/aymane/COURS/Projet antlr/s.g:37:9: ']]>'
    {
        MATCHS(lit_29); 
        if  (HASEXCEPTION())
        {
            goto ruleT__38Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__38Ex; /* Prevent compiler warnings */
    ruleT__38Ex: ;

}
// $ANTLR end T__38

//   Comes from: 38:7: ( '</description>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__39
 *
 * Looks to match the characters the constitute the token T__39
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__39(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__39;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:38:7: ( '</description>' )
    // /home/aymane/COURS/Projet antlr/s.g:38:9: '</description>'
    {
        MATCHS(lit_30); 
        if  (HASEXCEPTION())
        {
            goto ruleT__39Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__39Ex; /* Prevent compiler warnings */
    ruleT__39Ex: ;

}
// $ANTLR end T__39

//   Comes from: 39:7: ( '<styleUrl>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__40
 *
 * Looks to match the characters the constitute the token T__40
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__40(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__40;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:39:7: ( '<styleUrl>' )
    // /home/aymane/COURS/Projet antlr/s.g:39:9: '<styleUrl>'
    {
        MATCHS(lit_31); 
        if  (HASEXCEPTION())
        {
            goto ruleT__40Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__40Ex; /* Prevent compiler warnings */
    ruleT__40Ex: ;

}
// $ANTLR end T__40

//   Comes from: 40:7: ( '</styleUrl>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__41
 *
 * Looks to match the characters the constitute the token T__41
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__41(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__41;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:40:7: ( '</styleUrl>' )
    // /home/aymane/COURS/Projet antlr/s.g:40:9: '</styleUrl>'
    {
        MATCHS(lit_32); 
        if  (HASEXCEPTION())
        {
            goto ruleT__41Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__41Ex; /* Prevent compiler warnings */
    ruleT__41Ex: ;

}
// $ANTLR end T__41

//   Comes from: 41:7: ( '<Point>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__42
 *
 * Looks to match the characters the constitute the token T__42
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__42(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__42;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:41:7: ( '<Point>' )
    // /home/aymane/COURS/Projet antlr/s.g:41:9: '<Point>'
    {
        MATCHS(lit_33); 
        if  (HASEXCEPTION())
        {
            goto ruleT__42Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__42Ex; /* Prevent compiler warnings */
    ruleT__42Ex: ;

}
// $ANTLR end T__42

//   Comes from: 42:7: ( '</Point>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__43
 *
 * Looks to match the characters the constitute the token T__43
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__43(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__43;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:42:7: ( '</Point>' )
    // /home/aymane/COURS/Projet antlr/s.g:42:9: '</Point>'
    {
        MATCHS(lit_34); 
        if  (HASEXCEPTION())
        {
            goto ruleT__43Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__43Ex; /* Prevent compiler warnings */
    ruleT__43Ex: ;

}
// $ANTLR end T__43

//   Comes from: 43:7: ( '<coordinates>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__44
 *
 * Looks to match the characters the constitute the token T__44
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__44(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__44;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:43:7: ( '<coordinates>' )
    // /home/aymane/COURS/Projet antlr/s.g:43:9: '<coordinates>'
    {
        MATCHS(lit_35); 
        if  (HASEXCEPTION())
        {
            goto ruleT__44Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__44Ex; /* Prevent compiler warnings */
    ruleT__44Ex: ;

}
// $ANTLR end T__44

//   Comes from: 44:7: ( '</coordinates>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__45
 *
 * Looks to match the characters the constitute the token T__45
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__45(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__45;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:44:7: ( '</coordinates>' )
    // /home/aymane/COURS/Projet antlr/s.g:44:9: '</coordinates>'
    {
        MATCHS(lit_36); 
        if  (HASEXCEPTION())
        {
            goto ruleT__45Ex;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__45Ex; /* Prevent compiler warnings */
    ruleT__45Ex: ;

}
// $ANTLR end T__45

//   Comes from: 77:5: ( ( '-' )? ( '.' | '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COO
 *
 * Looks to match the characters the constitute the token COO
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOO(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COO;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:77:5: ( ( '-' )? ( '.' | '0' .. '9' )+ )
    // /home/aymane/COURS/Projet antlr/s.g:77:7: ( '-' )? ( '.' | '0' .. '9' )+
    {

        // /home/aymane/COURS/Projet antlr/s.g:77:7: ( '-' )?
        {
            int alt1=2;
            switch ( LA(1) ) 
            {
                case '-':
                	{
                		alt1=1;
                	}
                    break;
            }

            switch (alt1) 
            {
        	case 1:
        	    // /home/aymane/COURS/Projet antlr/s.g:77:8: '-'
        	    {
        	        MATCHC('-'); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCOOEx;
        	        }


        	    }
        	    break;

            }
        }
        // /home/aymane/COURS/Projet antlr/s.g:77:14: ( '.' | '0' .. '9' )+
        {
            int cnt2=0;

            for (;;)
            {
                int alt2=2;
        	switch ( LA(1) ) 
        	{
        	case '.':
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt2=1;
        		}
        	    break;

        	}

        	switch (alt2) 
        	{
        	    case 1:
        	        // /home/aymane/COURS/Projet antlr/s.g:
        	        {
        	            if ( LA(1) == '.' || ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleCOOEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt2 >= 1 )
        		{
        		    goto loop2;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleCOOEx;
        	}
        	cnt2++;
            }
            loop2: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleCOOEx; /* Prevent compiler warnings */
    ruleCOOEx: ;

}
// $ANTLR end COO

//   Comes from: 82:2: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | ' ' | 'É' | 'ô' | 'é' | 'è' | 'ö' | 'ë' | '\\'' | 'î' | 'Î' | 'ç' | 'â' | 'ê' | 'à' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NOM
 *
 * Looks to match the characters the constitute the token NOM
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNOM(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NOM;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:82:2: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | ' ' | 'É' | 'ô' | 'é' | 'è' | 'ö' | 'ë' | '\\'' | 'î' | 'Î' | 'ç' | 'â' | 'ê' | 'à' )* )
    // /home/aymane/COURS/Projet antlr/s.g:82:3: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | ' ' | 'É' | 'ô' | 'é' | 'è' | 'ö' | 'ë' | '\\'' | 'î' | 'Î' | 'ç' | 'â' | 'ê' | 'à' )*
    {

        // /home/aymane/COURS/Projet antlr/s.g:82:3: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | ' ' | 'É' | 'ô' | 'é' | 'è' | 'ö' | 'ë' | '\\'' | 'î' | 'Î' | 'ç' | 'â' | 'ê' | 'à' )*

        for (;;)
        {
            int alt3=2;
            switch ( LA(1) ) 
            {
            case ' ':
            case '\'':
            case '-':
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            case 0x00C9:
            case 0x00CE:
            case 0x00E0:
            case 0x00E2:
            case 0x00E7:
            case 0x00E8:
            case 0x00E9:
            case 0x00EA:
            case 0x00EB:
            case 0x00EE:
            case 0x00F4:
            case 0x00F6:
            	{
            		alt3=1;
            	}
                break;

            }

            switch (alt3) 
            {
        	case 1:
        	    // /home/aymane/COURS/Projet antlr/s.g:
        	    {
        	        if ( LA(1) == ' ' || LA(1) == '\'' || LA(1) == '-' || ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) || LA(1) == 0x00C9 || LA(1) == 0x00CE || LA(1) == 0x00E0 || LA(1) == 0x00E2 || ((LA(1) >= 0x00E7) && (LA(1) <= 0x00EB)) || LA(1) == 0x00EE || LA(1) == 0x00F4 || LA(1) == 0x00F6 )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleNOMEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop3;	/* break out of the loop */
        	    break;
            }
        }
        loop3: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleNOMEx; /* Prevent compiler warnings */
    ruleNOMEx: ;

}
// $ANTLR end NOM

//   Comes from: 87:6: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | ' ' | '!' | '\"' | ';' | ',' | '&' | '/' | '.' | ':' | '?' | ']' | '#' | '=' | 'ô' | 'é' | 'è' | 'ö' | 'ë' | '\\'' | 'î' | 'Î' | 'É' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ALPHA
 *
 * Looks to match the characters the constitute the token ALPHA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mALPHA(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ALPHA;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:87:6: ( ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | ' ' | '!' | '\"' | ';' | ',' | '&' | '/' | '.' | ':' | '?' | ']' | '#' | '=' | 'ô' | 'é' | 'è' | 'ö' | 'ë' | '\\'' | 'î' | 'Î' | 'É' )+ )
    // /home/aymane/COURS/Projet antlr/s.g:87:8: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | ' ' | '!' | '\"' | ';' | ',' | '&' | '/' | '.' | ':' | '?' | ']' | '#' | '=' | 'ô' | 'é' | 'è' | 'ö' | 'ë' | '\\'' | 'î' | 'Î' | 'É' )+
    {
        // /home/aymane/COURS/Projet antlr/s.g:87:8: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '-' | ' ' | '!' | '\"' | ';' | ',' | '&' | '/' | '.' | ':' | '?' | ']' | '#' | '=' | 'ô' | 'é' | 'è' | 'ö' | 'ë' | '\\'' | 'î' | 'Î' | 'É' )+
        {
            int cnt4=0;

            for (;;)
            {
                int alt4=2;
        	switch ( LA(1) ) 
        	{
        	case ' ':
        	case '!':
        	case '"':
        	case '#':
        	case '&':
        	case '\'':
        	case ',':
        	case '-':
        	case '.':
        	case '/':
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        	case ':':
        	case ';':
        	case '=':
        	case '?':
        	case 'A':
        	case 'B':
        	case 'C':
        	case 'D':
        	case 'E':
        	case 'F':
        	case 'G':
        	case 'H':
        	case 'I':
        	case 'J':
        	case 'K':
        	case 'L':
        	case 'M':
        	case 'N':
        	case 'O':
        	case 'P':
        	case 'Q':
        	case 'R':
        	case 'S':
        	case 'T':
        	case 'U':
        	case 'V':
        	case 'W':
        	case 'X':
        	case 'Y':
        	case 'Z':
        	case ']':
        	case 'a':
        	case 'b':
        	case 'c':
        	case 'd':
        	case 'e':
        	case 'f':
        	case 'g':
        	case 'h':
        	case 'i':
        	case 'j':
        	case 'k':
        	case 'l':
        	case 'm':
        	case 'n':
        	case 'o':
        	case 'p':
        	case 'q':
        	case 'r':
        	case 's':
        	case 't':
        	case 'u':
        	case 'v':
        	case 'w':
        	case 'x':
        	case 'y':
        	case 'z':
        	case 0x00C9:
        	case 0x00CE:
        	case 0x00E8:
        	case 0x00E9:
        	case 0x00EB:
        	case 0x00EE:
        	case 0x00F4:
        	case 0x00F6:
        		{
        			alt4=1;
        		}
        	    break;

        	}

        	switch (alt4) 
        	{
        	    case 1:
        	        // /home/aymane/COURS/Projet antlr/s.g:
        	        {
        	            if ( ((LA(1) >= ' ') && (LA(1) <= '#')) || ((LA(1) >= '&') && (LA(1) <= '\'')) || ((LA(1) >= ',') && (LA(1) <= ';')) || LA(1) == '=' || LA(1) == '?' || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == ']' || ((LA(1) >= 'a') && (LA(1) <= 'z')) || LA(1) == 0x00C9 || LA(1) == 0x00CE || ((LA(1) >= 0x00E8) && (LA(1) <= 0x00E9)) || LA(1) == 0x00EB || LA(1) == 0x00EE || LA(1) == 0x00F4 || LA(1) == 0x00F6 )
        	            {
        	                CONSUME();

        	            }
        	            else 
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();    goto ruleALPHAEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt4 >= 1 )
        		{
        		    goto loop4;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleALPHAEx;
        	}
        	cnt4++;
            }
            loop4: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleALPHAEx; /* Prevent compiler warnings */
    ruleALPHAEx: ;

}
// $ANTLR end ALPHA

//   Comes from: 90:5: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(psLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;
       
    
    // /home/aymane/COURS/Projet antlr/s.g:90:5: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
    // /home/aymane/COURS/Projet antlr/s.g:90:9: ( ' ' | '\\t' | '\\r' | '\\n' )
    {
        if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleWSEx;
        }

        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(psLexer ctx)
{
    {
        //  /home/aymane/COURS/Projet antlr/s.g:1:8: ( T__8 | T__9 | T__10 | T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | T__37 | T__38 | T__39 | T__40 | T__41 | T__42 | T__43 | T__44 | T__45 | COO | NOM | ALPHA | WS )
        
        ANTLR3_UINT32 alt5;

        alt5=42;

        alt5 = cdfa5.predict(ctx, RECOGNIZER, ISTREAM, &cdfa5);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt5) 
        {
    	case 1:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:10: T__8
    	    {
    	        /* 1:10: T__8 */
    	        mT__8(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:15: T__9
    	    {
    	        /* 1:15: T__9 */
    	        mT__9(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:20: T__10
    	    {
    	        /* 1:20: T__10 */
    	        mT__10(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:26: T__11
    	    {
    	        /* 1:26: T__11 */
    	        mT__11(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:32: T__12
    	    {
    	        /* 1:32: T__12 */
    	        mT__12(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:38: T__13
    	    {
    	        /* 1:38: T__13 */
    	        mT__13(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:44: T__14
    	    {
    	        /* 1:44: T__14 */
    	        mT__14(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:50: T__15
    	    {
    	        /* 1:50: T__15 */
    	        mT__15(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:56: T__16
    	    {
    	        /* 1:56: T__16 */
    	        mT__16(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:62: T__17
    	    {
    	        /* 1:62: T__17 */
    	        mT__17(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:68: T__18
    	    {
    	        /* 1:68: T__18 */
    	        mT__18(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:74: T__19
    	    {
    	        /* 1:74: T__19 */
    	        mT__19(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:80: T__20
    	    {
    	        /* 1:80: T__20 */
    	        mT__20(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:86: T__21
    	    {
    	        /* 1:86: T__21 */
    	        mT__21(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:92: T__22
    	    {
    	        /* 1:92: T__22 */
    	        mT__22(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:98: T__23
    	    {
    	        /* 1:98: T__23 */
    	        mT__23(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:104: T__24
    	    {
    	        /* 1:104: T__24 */
    	        mT__24(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:110: T__25
    	    {
    	        /* 1:110: T__25 */
    	        mT__25(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 19:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:116: T__26
    	    {
    	        /* 1:116: T__26 */
    	        mT__26(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 20:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:122: T__27
    	    {
    	        /* 1:122: T__27 */
    	        mT__27(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 21:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:128: T__28
    	    {
    	        /* 1:128: T__28 */
    	        mT__28(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 22:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:134: T__29
    	    {
    	        /* 1:134: T__29 */
    	        mT__29(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 23:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:140: T__30
    	    {
    	        /* 1:140: T__30 */
    	        mT__30(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 24:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:146: T__31
    	    {
    	        /* 1:146: T__31 */
    	        mT__31(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 25:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:152: T__32
    	    {
    	        /* 1:152: T__32 */
    	        mT__32(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 26:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:158: T__33
    	    {
    	        /* 1:158: T__33 */
    	        mT__33(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 27:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:164: T__34
    	    {
    	        /* 1:164: T__34 */
    	        mT__34(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 28:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:170: T__35
    	    {
    	        /* 1:170: T__35 */
    	        mT__35(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 29:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:176: T__36
    	    {
    	        /* 1:176: T__36 */
    	        mT__36(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 30:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:182: T__37
    	    {
    	        /* 1:182: T__37 */
    	        mT__37(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 31:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:188: T__38
    	    {
    	        /* 1:188: T__38 */
    	        mT__38(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 32:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:194: T__39
    	    {
    	        /* 1:194: T__39 */
    	        mT__39(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 33:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:200: T__40
    	    {
    	        /* 1:200: T__40 */
    	        mT__40(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 34:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:206: T__41
    	    {
    	        /* 1:206: T__41 */
    	        mT__41(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 35:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:212: T__42
    	    {
    	        /* 1:212: T__42 */
    	        mT__42(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 36:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:218: T__43
    	    {
    	        /* 1:218: T__43 */
    	        mT__43(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 37:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:224: T__44
    	    {
    	        /* 1:224: T__44 */
    	        mT__44(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 38:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:230: T__45
    	    {
    	        /* 1:230: T__45 */
    	        mT__45(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 39:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:236: COO
    	    {
    	        /* 1:236: COO */
    	        mCOO(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 40:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:240: NOM
    	    {
    	        /* 1:240: NOM */
    	        mNOM(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 41:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:244: ALPHA
    	    {
    	        /* 1:244: ALPHA */
    	        mALPHA(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 42:
    	    // /home/aymane/COURS/Projet antlr/s.g:1:250: WS
    	    {
    	        /* 1:250: WS */
    	        mWS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
