/** \file
 *  This C source file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : /home/aymane/COURS/Projet antlr/s.g
 *     -                            On : 2011-05-29 12:39:53
 *     -                for the parser : sParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "sParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   psParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  psParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->psParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->psParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER				ctx->pParser  
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   sParserTokenNames[42+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "NOM",
        (pANTLR3_UINT8) "COO",
        (pANTLR3_UINT8) "ALPHA",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'<'",
        (pANTLR3_UINT8) "'>'",
        (pANTLR3_UINT8) "'<Document>'",
        (pANTLR3_UINT8) "'<name>'",
        (pANTLR3_UINT8) "'</name>'",
        (pANTLR3_UINT8) "'</Document>'",
        (pANTLR3_UINT8) "'</kml>'",
        (pANTLR3_UINT8) "'<Style'",
        (pANTLR3_UINT8) "'<IconStyle>'",
        (pANTLR3_UINT8) "'<scale>'",
        (pANTLR3_UINT8) "'</scale>'",
        (pANTLR3_UINT8) "'<Icon>'",
        (pANTLR3_UINT8) "'<href>'",
        (pANTLR3_UINT8) "'</href>'",
        (pANTLR3_UINT8) "'</Icon>'",
        (pANTLR3_UINT8) "'</IconStyle>'",
        (pANTLR3_UINT8) "'<LabelStyle>'",
        (pANTLR3_UINT8) "'<color>'",
        (pANTLR3_UINT8) "'</color>'",
        (pANTLR3_UINT8) "'</LabelStyle>'",
        (pANTLR3_UINT8) "'</Style>'",
        (pANTLR3_UINT8) "'<Placemark>'",
        (pANTLR3_UINT8) "'</Placemark>'",
        (pANTLR3_UINT8) "'<description>'",
        (pANTLR3_UINT8) "'<![CDATA['",
        (pANTLR3_UINT8) "'>population:'",
        (pANTLR3_UINT8) "'<br>'",
        (pANTLR3_UINT8) "'<a'",
        (pANTLR3_UINT8) "'</a><'",
        (pANTLR3_UINT8) "'</font>'",
        (pANTLR3_UINT8) "']]>'",
        (pANTLR3_UINT8) "'</description>'",
        (pANTLR3_UINT8) "'<styleUrl>'",
        (pANTLR3_UINT8) "'</styleUrl>'",
        (pANTLR3_UINT8) "'<Point>'",
        (pANTLR3_UINT8) "'</Point>'",
        (pANTLR3_UINT8) "'<coordinates>'",
        (pANTLR3_UINT8) "'</coordinates>'"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static void	s    (psParser ctx);
static void	styletag    (psParser ctx);
static void	liste    (psParser ctx);
static void	ville    (psParser ctx);
static coord	coordonnees    (psParser ctx);
static sParser_population_return	population    (psParser ctx);
static void	coordinate    (psParser ctx);
static sParser_bin_return	bin    (psParser ctx);
static sParser_name_return	name    (psParser ctx);
static void	sParserFree(psParser ctx);
static void     sParserReset (psParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/aymane/COURS/Projet antlr/s.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new sParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API psParser
sParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return sParserNewSSD(instream, NULL);
}

/** \brief Create a new sParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API psParser
sParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    psParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (psParser) ANTLR3_CALLOC(1, sizeof(sParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in sParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our sParser interface
     */
    ctx->s	= s;
    ctx->styletag	= styletag;
    ctx->liste	= liste;
    ctx->ville	= ville;
    ctx->coordonnees	= coordonnees;
    ctx->population	= population;
    ctx->coordinate	= coordinate;
    ctx->bin	= bin;
    ctx->name	= name;
    ctx->free			= sParserFree;
    ctx->reset			= sParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = sParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
sParserReset (psParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 sParserFree(psParser ctx)
 {
    /* Free any scope memory
     */
    
        
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return sParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_s28  */
static	ANTLR3_BITWORD FOLLOW_8_in_s28_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_s28	= { FOLLOW_8_in_s28_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_s29  */
static	ANTLR3_BITWORD FOLLOW_bin_in_s29_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_s29	= { FOLLOW_bin_in_s29_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_s30  */
static	ANTLR3_BITWORD FOLLOW_9_in_s30_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_s30	= { FOLLOW_9_in_s30_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_s32  */
static	ANTLR3_BITWORD FOLLOW_8_in_s32_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_s32	= { FOLLOW_8_in_s32_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_s33  */
static	ANTLR3_BITWORD FOLLOW_bin_in_s33_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_s33	= { FOLLOW_bin_in_s33_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_s34  */
static	ANTLR3_BITWORD FOLLOW_9_in_s34_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_s34	= { FOLLOW_9_in_s34_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_10_in_s37  */
static	ANTLR3_BITWORD FOLLOW_10_in_s37_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_10_in_s37	= { FOLLOW_10_in_s37_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_s38  */
static	ANTLR3_BITWORD FOLLOW_11_in_s38_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_s38	= { FOLLOW_11_in_s38_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_s39  */
static	ANTLR3_BITWORD FOLLOW_bin_in_s39_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_s39	= { FOLLOW_bin_in_s39_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_12_in_s40  */
static	ANTLR3_BITWORD FOLLOW_12_in_s40_bits[]	= { ANTLR3_UINT64_LIT(0x000000002000A000) };
static  ANTLR3_BITSET_LIST FOLLOW_12_in_s40	= { FOLLOW_12_in_s40_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_styletag_in_s44  */
static	ANTLR3_BITWORD FOLLOW_styletag_in_s44_bits[]	= { ANTLR3_UINT64_LIT(0x0000000020002000) };
static  ANTLR3_BITSET_LIST FOLLOW_styletag_in_s44	= { FOLLOW_styletag_in_s44_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_liste_in_s46  */
static	ANTLR3_BITWORD FOLLOW_liste_in_s46_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002000) };
static  ANTLR3_BITSET_LIST FOLLOW_liste_in_s46	= { FOLLOW_liste_in_s46_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_13_in_s48  */
static	ANTLR3_BITWORD FOLLOW_13_in_s48_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_13_in_s48	= { FOLLOW_13_in_s48_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_s49  */
static	ANTLR3_BITWORD FOLLOW_14_in_s49_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_s49	= { FOLLOW_14_in_s49_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_s51  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_s51_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_s51	= { FOLLOW_EOF_in_s51_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_styletag62  */
static	ANTLR3_BITWORD FOLLOW_15_in_styletag62_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_styletag62	= { FOLLOW_15_in_styletag62_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_styletag64  */
static	ANTLR3_BITWORD FOLLOW_bin_in_styletag64_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_styletag64	= { FOLLOW_bin_in_styletag64_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_styletag66  */
static	ANTLR3_BITWORD FOLLOW_9_in_styletag66_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010000) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_styletag66	= { FOLLOW_9_in_styletag66_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_styletag67  */
static	ANTLR3_BITWORD FOLLOW_16_in_styletag67_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_styletag67	= { FOLLOW_16_in_styletag67_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_styletag68  */
static	ANTLR3_BITWORD FOLLOW_17_in_styletag68_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_styletag68	= { FOLLOW_17_in_styletag68_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_coordinate_in_styletag69  */
static	ANTLR3_BITWORD FOLLOW_coordinate_in_styletag69_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_coordinate_in_styletag69	= { FOLLOW_coordinate_in_styletag69_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_styletag70  */
static	ANTLR3_BITWORD FOLLOW_18_in_styletag70_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_styletag70	= { FOLLOW_18_in_styletag70_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_styletag71  */
static	ANTLR3_BITWORD FOLLOW_19_in_styletag71_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000100000) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_styletag71	= { FOLLOW_19_in_styletag71_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_20_in_styletag72  */
static	ANTLR3_BITWORD FOLLOW_20_in_styletag72_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_20_in_styletag72	= { FOLLOW_20_in_styletag72_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_styletag73  */
static	ANTLR3_BITWORD FOLLOW_bin_in_styletag73_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200000) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_styletag73	= { FOLLOW_bin_in_styletag73_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_styletag74  */
static	ANTLR3_BITWORD FOLLOW_21_in_styletag74_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_styletag74	= { FOLLOW_21_in_styletag74_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_styletag75  */
static	ANTLR3_BITWORD FOLLOW_22_in_styletag75_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_styletag75	= { FOLLOW_22_in_styletag75_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_23_in_styletag76  */
static	ANTLR3_BITWORD FOLLOW_23_in_styletag76_bits[]	= { ANTLR3_UINT64_LIT(0x0000000001000000) };
static  ANTLR3_BITSET_LIST FOLLOW_23_in_styletag76	= { FOLLOW_23_in_styletag76_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_24_in_styletag77  */
static	ANTLR3_BITWORD FOLLOW_24_in_styletag77_bits[]	= { ANTLR3_UINT64_LIT(0x0000000002000000) };
static  ANTLR3_BITSET_LIST FOLLOW_24_in_styletag77	= { FOLLOW_24_in_styletag77_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_25_in_styletag81  */
static	ANTLR3_BITWORD FOLLOW_25_in_styletag81_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_25_in_styletag81	= { FOLLOW_25_in_styletag81_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_name_in_styletag83  */
static	ANTLR3_BITWORD FOLLOW_name_in_styletag83_bits[]	= { ANTLR3_UINT64_LIT(0x0000000004000000) };
static  ANTLR3_BITSET_LIST FOLLOW_name_in_styletag83	= { FOLLOW_name_in_styletag83_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_26_in_styletag85  */
static	ANTLR3_BITWORD FOLLOW_26_in_styletag85_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_26_in_styletag85	= { FOLLOW_26_in_styletag85_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_styletag89  */
static	ANTLR3_BITWORD FOLLOW_17_in_styletag89_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000020) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_styletag89	= { FOLLOW_17_in_styletag89_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_coordinate_in_styletag90  */
static	ANTLR3_BITWORD FOLLOW_coordinate_in_styletag90_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000040000) };
static  ANTLR3_BITSET_LIST FOLLOW_coordinate_in_styletag90	= { FOLLOW_coordinate_in_styletag90_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_styletag91  */
static	ANTLR3_BITWORD FOLLOW_18_in_styletag91_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000000) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_styletag91	= { FOLLOW_18_in_styletag91_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_27_in_styletag92  */
static	ANTLR3_BITWORD FOLLOW_27_in_styletag92_bits[]	= { ANTLR3_UINT64_LIT(0x0000000010000000) };
static  ANTLR3_BITSET_LIST FOLLOW_27_in_styletag92	= { FOLLOW_27_in_styletag92_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_28_in_styletag96  */
static	ANTLR3_BITWORD FOLLOW_28_in_styletag96_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008000) };
static  ANTLR3_BITSET_LIST FOLLOW_28_in_styletag96	= { FOLLOW_28_in_styletag96_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_styletag_in_styletag98  */
static	ANTLR3_BITWORD FOLLOW_styletag_in_styletag98_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_styletag_in_styletag98	= { FOLLOW_styletag_in_styletag98_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_29_in_liste115  */
static	ANTLR3_BITWORD FOLLOW_29_in_liste115_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000800) };
static  ANTLR3_BITSET_LIST FOLLOW_29_in_liste115	= { FOLLOW_29_in_liste115_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ville_in_liste116  */
static	ANTLR3_BITWORD FOLLOW_ville_in_liste116_bits[]	= { ANTLR3_UINT64_LIT(0x0000000040000000) };
static  ANTLR3_BITSET_LIST FOLLOW_ville_in_liste116	= { FOLLOW_ville_in_liste116_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_30_in_liste117  */
static	ANTLR3_BITWORD FOLLOW_30_in_liste117_bits[]	= { ANTLR3_UINT64_LIT(0x0000000020000000) };
static  ANTLR3_BITSET_LIST FOLLOW_30_in_liste117	= { FOLLOW_30_in_liste117_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_liste_in_liste118  */
static	ANTLR3_BITWORD FOLLOW_liste_in_liste118_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_liste_in_liste118	= { FOLLOW_liste_in_liste118_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_11_in_ville136  */
static	ANTLR3_BITWORD FOLLOW_11_in_ville136_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_11_in_ville136	= { FOLLOW_11_in_ville136_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_name_in_ville139  */
static	ANTLR3_BITWORD FOLLOW_name_in_ville139_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000001000) };
static  ANTLR3_BITSET_LIST FOLLOW_name_in_ville139	= { FOLLOW_name_in_ville139_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_12_in_ville140  */
static	ANTLR3_BITWORD FOLLOW_12_in_ville140_bits[]	= { ANTLR3_UINT64_LIT(0x0000000080000000) };
static  ANTLR3_BITSET_LIST FOLLOW_12_in_ville140	= { FOLLOW_12_in_ville140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_31_in_ville143  */
static	ANTLR3_BITWORD FOLLOW_31_in_ville143_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100000000) };
static  ANTLR3_BITSET_LIST FOLLOW_31_in_ville143	= { FOLLOW_31_in_ville143_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_32_in_ville144  */
static	ANTLR3_BITWORD FOLLOW_32_in_ville144_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_32_in_ville144	= { FOLLOW_32_in_ville144_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_8_in_ville146  */
static	ANTLR3_BITWORD FOLLOW_8_in_ville146_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_8_in_ville146	= { FOLLOW_8_in_ville146_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_ville148  */
static	ANTLR3_BITWORD FOLLOW_bin_in_ville148_bits[]	= { ANTLR3_UINT64_LIT(0x0000000200000000) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_ville148	= { FOLLOW_bin_in_ville148_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_33_in_ville150  */
static	ANTLR3_BITWORD FOLLOW_33_in_ville150_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_33_in_ville150	= { FOLLOW_33_in_ville150_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_population_in_ville154  */
static	ANTLR3_BITWORD FOLLOW_population_in_ville154_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000000) };
static  ANTLR3_BITSET_LIST FOLLOW_population_in_ville154	= { FOLLOW_population_in_ville154_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_34_in_ville156  */
static	ANTLR3_BITWORD FOLLOW_34_in_ville156_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_34_in_ville156	= { FOLLOW_34_in_ville156_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_ville157  */
static	ANTLR3_BITWORD FOLLOW_bin_in_ville157_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000000) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_ville157	= { FOLLOW_bin_in_ville157_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_34_in_ville159  */
static	ANTLR3_BITWORD FOLLOW_34_in_ville159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_34_in_ville159	= { FOLLOW_34_in_ville159_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_ville161  */
static	ANTLR3_BITWORD FOLLOW_bin_in_ville161_bits[]	= { ANTLR3_UINT64_LIT(0x0000000800000000) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_ville161	= { FOLLOW_bin_in_ville161_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_35_in_ville163  */
static	ANTLR3_BITWORD FOLLOW_35_in_ville163_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_35_in_ville163	= { FOLLOW_35_in_ville163_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_ville165  */
static	ANTLR3_BITWORD FOLLOW_bin_in_ville165_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_ville165	= { FOLLOW_bin_in_ville165_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_ville167  */
static	ANTLR3_BITWORD FOLLOW_9_in_ville167_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_ville167	= { FOLLOW_9_in_ville167_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_name_in_ville169  */
static	ANTLR3_BITWORD FOLLOW_name_in_ville169_bits[]	= { ANTLR3_UINT64_LIT(0x0000001000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_name_in_ville169	= { FOLLOW_name_in_ville169_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_36_in_ville171  */
static	ANTLR3_BITWORD FOLLOW_36_in_ville171_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_36_in_ville171	= { FOLLOW_36_in_ville171_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_name_in_ville173  */
static	ANTLR3_BITWORD FOLLOW_name_in_ville173_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000200) };
static  ANTLR3_BITSET_LIST FOLLOW_name_in_ville173	= { FOLLOW_name_in_ville173_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_9_in_ville175  */
static	ANTLR3_BITWORD FOLLOW_9_in_ville175_bits[]	= { ANTLR3_UINT64_LIT(0x0000002000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_9_in_ville175	= { FOLLOW_9_in_ville175_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_37_in_ville177  */
static	ANTLR3_BITWORD FOLLOW_37_in_ville177_bits[]	= { ANTLR3_UINT64_LIT(0x0000004000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_37_in_ville177	= { FOLLOW_37_in_ville177_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_38_in_ville179  */
static	ANTLR3_BITWORD FOLLOW_38_in_ville179_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_38_in_ville179	= { FOLLOW_38_in_ville179_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_39_in_ville185  */
static	ANTLR3_BITWORD FOLLOW_39_in_ville185_bits[]	= { ANTLR3_UINT64_LIT(0x0000010000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_39_in_ville185	= { FOLLOW_39_in_ville185_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_40_in_ville186  */
static	ANTLR3_BITWORD FOLLOW_40_in_ville186_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_40_in_ville186	= { FOLLOW_40_in_ville186_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_ville187  */
static	ANTLR3_BITWORD FOLLOW_bin_in_ville187_bits[]	= { ANTLR3_UINT64_LIT(0x0000020000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_ville187	= { FOLLOW_bin_in_ville187_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_41_in_ville188  */
static	ANTLR3_BITWORD FOLLOW_41_in_ville188_bits[]	= { ANTLR3_UINT64_LIT(0x0000040000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_41_in_ville188	= { FOLLOW_41_in_ville188_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_42_in_ville193  */
static	ANTLR3_BITWORD FOLLOW_42_in_ville193_bits[]	= { ANTLR3_UINT64_LIT(0x0000100000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_42_in_ville193	= { FOLLOW_42_in_ville193_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_coordonnees_in_ville194  */
static	ANTLR3_BITWORD FOLLOW_coordonnees_in_ville194_bits[]	= { ANTLR3_UINT64_LIT(0x0000080000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_coordonnees_in_ville194	= { FOLLOW_coordonnees_in_ville194_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_43_in_ville195  */
static	ANTLR3_BITWORD FOLLOW_43_in_ville195_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_43_in_ville195	= { FOLLOW_43_in_ville195_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_44_in_coordonnees217  */
static	ANTLR3_BITWORD FOLLOW_44_in_coordonnees217_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000040) };
static  ANTLR3_BITSET_LIST FOLLOW_44_in_coordonnees217	= { FOLLOW_44_in_coordonnees217_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_bin_in_coordonnees221  */
static	ANTLR3_BITWORD FOLLOW_bin_in_coordonnees221_bits[]	= { ANTLR3_UINT64_LIT(0x0000200000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_bin_in_coordonnees221	= { FOLLOW_bin_in_coordonnees221_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_45_in_coordonnees223  */
static	ANTLR3_BITWORD FOLLOW_45_in_coordonnees223_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_45_in_coordonnees223	= { FOLLOW_45_in_coordonnees223_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NOM_in_population241  */
static	ANTLR3_BITWORD FOLLOW_NOM_in_population241_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NOM_in_population241	= { FOLLOW_NOM_in_population241_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COO_in_coordinate256  */
static	ANTLR3_BITWORD FOLLOW_COO_in_coordinate256_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_COO_in_coordinate256	= { FOLLOW_COO_in_coordinate256_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ALPHA_in_bin267  */
static	ANTLR3_BITWORD FOLLOW_ALPHA_in_bin267_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ALPHA_in_bin267	= { FOLLOW_ALPHA_in_bin267_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NOM_in_name280  */
static	ANTLR3_BITWORD FOLLOW_NOM_in_name280_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NOM_in_name280	= { FOLLOW_NOM_in_name280_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start s
 * /home/aymane/COURS/Projet antlr/s.g:13:1: s : '<' bin '>' '<' bin '>' '<Document>' '<name>' bin '</name>' styletag liste '</Document>' '</kml>' EOF ;
 */
static void
s(psParser ctx)
{   
    /* Initialize rule variables
     */


    {
        // /home/aymane/COURS/Projet antlr/s.g:13:4: ( '<' bin '>' '<' bin '>' '<Document>' '<name>' bin '</name>' styletag liste '</Document>' '</kml>' EOF )
        // /home/aymane/COURS/Projet antlr/s.g:13:5: '<' bin '>' '<' bin '>' '<Document>' '<name>' bin '</name>' styletag liste '</Document>' '</kml>' EOF
        {
             MATCHT(8, &FOLLOW_8_in_s28); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

            FOLLOWPUSH(FOLLOW_bin_in_s29);
            bin(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

             MATCHT(9, &FOLLOW_9_in_s30); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

             MATCHT(8, &FOLLOW_8_in_s32); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

            FOLLOWPUSH(FOLLOW_bin_in_s33);
            bin(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

             MATCHT(9, &FOLLOW_9_in_s34); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

             MATCHT(10, &FOLLOW_10_in_s37); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

             MATCHT(11, &FOLLOW_11_in_s38); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

            FOLLOWPUSH(FOLLOW_bin_in_s39);
            bin(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

             MATCHT(12, &FOLLOW_12_in_s40); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

            FOLLOWPUSH(FOLLOW_styletag_in_s44);
            styletag(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

            FOLLOWPUSH(FOLLOW_liste_in_s46);
            liste(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

             MATCHT(13, &FOLLOW_13_in_s48); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

             MATCHT(14, &FOLLOW_14_in_s49); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }

             MATCHT(EOF, &FOLLOW_EOF_in_s51); 
            if  (HASEXCEPTION())
            {
                goto rulesEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesEx; /* Prevent compiler warnings */
    rulesEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return ;
}
/* $ANTLR end s */

/** 
 * $ANTLR start styletag
 * /home/aymane/COURS/Projet antlr/s.g:18:1: styletag : ( '<Style' bin '>' '<IconStyle>' '<scale>' coordinate '</scale>' '<Icon>' '<href>' bin '</href>' '</Icon>' '</IconStyle>' '<LabelStyle>' '<color>' name '</color>' '<scale>' coordinate '</scale>' '</LabelStyle>' '</Style>' styletag | );
 */
static void
styletag(psParser ctx)
{   
    /* Initialize rule variables
     */


    {
        {
            //  /home/aymane/COURS/Projet antlr/s.g:19:2: ( '<Style' bin '>' '<IconStyle>' '<scale>' coordinate '</scale>' '<Icon>' '<href>' bin '</href>' '</Icon>' '</IconStyle>' '<LabelStyle>' '<color>' name '</color>' '<scale>' coordinate '</scale>' '</LabelStyle>' '</Style>' styletag | )
            
            ANTLR3_UINT32 alt1;

            alt1=2;

            switch ( LA(1) ) 
            {
            case 15:
            	{
            		alt1=1;
            	}
                break;
            case 13:
            case 29:
            	{
            		alt1=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 1;
                EXCEPTION->state        = 0;


                goto rulestyletagEx;
            }

            switch (alt1) 
            {
        	case 1:
        	    // /home/aymane/COURS/Projet antlr/s.g:19:4: '<Style' bin '>' '<IconStyle>' '<scale>' coordinate '</scale>' '<Icon>' '<href>' bin '</href>' '</Icon>' '</IconStyle>' '<LabelStyle>' '<color>' name '</color>' '<scale>' coordinate '</scale>' '</LabelStyle>' '</Style>' styletag
        	    {
        	         MATCHT(15, &FOLLOW_15_in_styletag62); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_bin_in_styletag64);
        	        bin(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(9, &FOLLOW_9_in_styletag66); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(16, &FOLLOW_16_in_styletag67); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(17, &FOLLOW_17_in_styletag68); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_coordinate_in_styletag69);
        	        coordinate(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(18, &FOLLOW_18_in_styletag70); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(19, &FOLLOW_19_in_styletag71); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(20, &FOLLOW_20_in_styletag72); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_bin_in_styletag73);
        	        bin(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(21, &FOLLOW_21_in_styletag74); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(22, &FOLLOW_22_in_styletag75); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(23, &FOLLOW_23_in_styletag76); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(24, &FOLLOW_24_in_styletag77); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(25, &FOLLOW_25_in_styletag81); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_name_in_styletag83);
        	        name(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(26, &FOLLOW_26_in_styletag85); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(17, &FOLLOW_17_in_styletag89); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_coordinate_in_styletag90);
        	        coordinate(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(18, &FOLLOW_18_in_styletag91); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(27, &FOLLOW_27_in_styletag92); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	         MATCHT(28, &FOLLOW_28_in_styletag96); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_styletag_in_styletag98);
        	        styletag(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestyletagEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // /home/aymane/COURS/Projet antlr/s.g:24:2: 
        	    {
        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulestyletagEx; /* Prevent compiler warnings */
    rulestyletagEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return ;
}
/* $ANTLR end styletag */

/** 
 * $ANTLR start liste
 * /home/aymane/COURS/Projet antlr/s.g:26:1: liste : ( '<Placemark>' ville '</Placemark>' liste | );
 */
static void
liste(psParser ctx)
{   
    /* Initialize rule variables
     */


    {
        {
            //  /home/aymane/COURS/Projet antlr/s.g:26:7: ( '<Placemark>' ville '</Placemark>' liste | )
            
            ANTLR3_UINT32 alt2;

            alt2=2;

            switch ( LA(1) ) 
            {
            case 29:
            	{
            		alt2=1;
            	}
                break;
            case 13:
            	{
            		alt2=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto rulelisteEx;
            }

            switch (alt2) 
            {
        	case 1:
        	    // /home/aymane/COURS/Projet antlr/s.g:26:9: '<Placemark>' ville '</Placemark>' liste
        	    {
        	         MATCHT(29, &FOLLOW_29_in_liste115); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelisteEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_ville_in_liste116);
        	        ville(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelisteEx;
        	        }

        	         MATCHT(30, &FOLLOW_30_in_liste117); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelisteEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_liste_in_liste118);
        	        liste(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulelisteEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // /home/aymane/COURS/Projet antlr/s.g:28:2: 
        	    {
        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulelisteEx; /* Prevent compiler warnings */
    rulelisteEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return ;
}
/* $ANTLR end liste */

/** 
 * $ANTLR start ville
 * /home/aymane/COURS/Projet antlr/s.g:30:1: ville : '<name>' nom_ville= name '</name>' '<description>' '<![CDATA[' '<' bin '>population:' pop= population '<br>' bin '<br>' bin '<a' bin '>' name '</a><' name '>' '</font>' ']]>' '</description>' '<styleUrl>' bin '</styleUrl>' '<Point>' coordonnees '</Point>' ;
 */
static void
ville(psParser ctx)
{   
    sParser_name_return nom_ville;
    #undef	RETURN_TYPE_nom_ville
    #define	RETURN_TYPE_nom_ville sParser_name_return

    sParser_population_return pop;
    #undef	RETURN_TYPE_pop
    #define	RETURN_TYPE_pop sParser_population_return

    /* Initialize rule variables
     */





    {
        // /home/aymane/COURS/Projet antlr/s.g:31:2: ( '<name>' nom_ville= name '</name>' '<description>' '<![CDATA[' '<' bin '>population:' pop= population '<br>' bin '<br>' bin '<a' bin '>' name '</a><' name '>' '</font>' ']]>' '</description>' '<styleUrl>' bin '</styleUrl>' '<Point>' coordonnees '</Point>' )
        // /home/aymane/COURS/Projet antlr/s.g:32:2: '<name>' nom_ville= name '</name>' '<description>' '<![CDATA[' '<' bin '>population:' pop= population '<br>' bin '<br>' bin '<a' bin '>' name '</a><' name '>' '</font>' ']]>' '</description>' '<styleUrl>' bin '</styleUrl>' '<Point>' coordonnees '</Point>'
        {
             MATCHT(11, &FOLLOW_11_in_ville136); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_name_in_ville139);
            nom_ville=name(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(12, &FOLLOW_12_in_ville140); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(31, &FOLLOW_31_in_ville143); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(32, &FOLLOW_32_in_ville144); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(8, &FOLLOW_8_in_ville146); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_bin_in_ville148);
            bin(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(33, &FOLLOW_33_in_ville150); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_population_in_ville154);
            pop=population(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(34, &FOLLOW_34_in_ville156); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_bin_in_ville157);
            bin(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(34, &FOLLOW_34_in_ville159); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_bin_in_ville161);
            bin(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(35, &FOLLOW_35_in_ville163); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_bin_in_ville165);
            bin(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(9, &FOLLOW_9_in_ville167); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_name_in_ville169);
            name(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(36, &FOLLOW_36_in_ville171); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_name_in_ville173);
            name(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(9, &FOLLOW_9_in_ville175); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(37, &FOLLOW_37_in_ville177); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(38, &FOLLOW_38_in_ville179); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(39, &FOLLOW_39_in_ville185); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(40, &FOLLOW_40_in_ville186); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_bin_in_ville187);
            bin(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(41, &FOLLOW_41_in_ville188); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(42, &FOLLOW_42_in_ville193); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            FOLLOWPUSH(FOLLOW_coordonnees_in_ville194);
            coordonnees(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

             MATCHT(43, &FOLLOW_43_in_ville195); 
            if  (HASEXCEPTION())
            {
                goto rulevilleEx;
            }

            {
                printf("%s,%d", ((STRSTREAM->toStringTT(STRSTREAM, nom_ville.start, nom_ville.stop))->chars),((STRSTREAM->toStringTT(STRSTREAM, pop.start, pop.stop))->toInt32((STRSTREAM->toStringTT(STRSTREAM, pop.start, pop.stop)))));
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulevilleEx; /* Prevent compiler warnings */
    rulevilleEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return ;
}
/* $ANTLR end ville */

/** 
 * $ANTLR start coordonnees
 * /home/aymane/COURS/Projet antlr/s.g:40:1: coordonnees returns [coord c] : '<coordinates>' b= bin '</coordinates>' ;
 */
static coord
coordonnees(psParser ctx)
{   
    coord c;

    sParser_bin_return b;
    #undef	RETURN_TYPE_b
    #define	RETURN_TYPE_b sParser_bin_return

    /* Initialize rule variables
     */


    {
        // /home/aymane/COURS/Projet antlr/s.g:41:2: ( '<coordinates>' b= bin '</coordinates>' )
        // /home/aymane/COURS/Projet antlr/s.g:41:4: '<coordinates>' b= bin '</coordinates>'
        {
             MATCHT(44, &FOLLOW_44_in_coordonnees217); 
            if  (HASEXCEPTION())
            {
                goto rulecoordonneesEx;
            }

            FOLLOWPUSH(FOLLOW_bin_in_coordonnees221);
            b=bin(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulecoordonneesEx;
            }

             MATCHT(45, &FOLLOW_45_in_coordonnees223); 
            if  (HASEXCEPTION())
            {
                goto rulecoordonneesEx;
            }

            {
                int i=0;int j=0; 

                	while(((STRSTREAM->toStringTT(STRSTREAM, b.start, b.stop))->chars[i]) != ',') {
                	c.longi[i]=((STRSTREAM->toStringTT(STRSTREAM, b.start, b.stop))->chars[i]); i++;
                	}
                	c.longi[i]='\0'; j=i+1;
                	while(((STRSTREAM->toStringTT(STRSTREAM, b.start, b.stop))->chars[j]) != ',') {
                	c.lat[j-i+1]=(STRSTREAM->toStringTT(STRSTREAM, b.start, b.stop))->chars[j]; j++;
                	} 
                	c.lat[j]='\0';
                	
                	if ((c.longi[0])=='-') (c.longi[strlen(c.longi)])='W'; else (c.longi[strlen(c.longi)])='E'; 
                	if ((c.lat[0])=='-') (c.lat[strlen(c.lat)])='S'; else (c.lat[strlen(c.lat)])='N';
                	printf("%s,%s\n",c.lat,c.longi); 
                	
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulecoordonneesEx; /* Prevent compiler warnings */
    rulecoordonneesEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return c;
}
/* $ANTLR end coordonnees */

/** 
 * $ANTLR start population
 * /home/aymane/COURS/Projet antlr/s.g:59:1: population : NOM ;
 */
static sParser_population_return
population(psParser ctx)
{   
    sParser_population_return retval;

    /* Initialize rule variables
     */


    retval.start = LT(1); retval.stop = retval.start;

    {
        // /home/aymane/COURS/Projet antlr/s.g:60:2: ( NOM )
        // /home/aymane/COURS/Projet antlr/s.g:60:4: NOM
        {
             MATCHT(NOM, &FOLLOW_NOM_in_population241); 
            if  (HASEXCEPTION())
            {
                goto rulepopulationEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepopulationEx; /* Prevent compiler warnings */
    rulepopulationEx: ;
    retval.stop = LT(-1);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return retval;
}
/* $ANTLR end population */

/** 
 * $ANTLR start coordinate
 * /home/aymane/COURS/Projet antlr/s.g:64:1: coordinate : COO ;
 */
static void
coordinate(psParser ctx)
{   
    /* Initialize rule variables
     */


    {
        // /home/aymane/COURS/Projet antlr/s.g:65:2: ( COO )
        // /home/aymane/COURS/Projet antlr/s.g:65:5: COO
        {
             MATCHT(COO, &FOLLOW_COO_in_coordinate256); 
            if  (HASEXCEPTION())
            {
                goto rulecoordinateEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulecoordinateEx; /* Prevent compiler warnings */
    rulecoordinateEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return ;
}
/* $ANTLR end coordinate */

/** 
 * $ANTLR start bin
 * /home/aymane/COURS/Projet antlr/s.g:69:1: bin : ALPHA ;
 */
static sParser_bin_return
bin(psParser ctx)
{   
    sParser_bin_return retval;

    /* Initialize rule variables
     */


    retval.start = LT(1); retval.stop = retval.start;

    {
        // /home/aymane/COURS/Projet antlr/s.g:69:5: ( ALPHA )
        // /home/aymane/COURS/Projet antlr/s.g:69:7: ALPHA
        {
             MATCHT(ALPHA, &FOLLOW_ALPHA_in_bin267); 
            if  (HASEXCEPTION())
            {
                goto rulebinEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulebinEx; /* Prevent compiler warnings */
    rulebinEx: ;
    retval.stop = LT(-1);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return retval;
}
/* $ANTLR end bin */

/** 
 * $ANTLR start name
 * /home/aymane/COURS/Projet antlr/s.g:73:1: name : NOM ;
 */
static sParser_name_return
name(psParser ctx)
{   
    sParser_name_return retval;

    /* Initialize rule variables
     */


    retval.start = LT(1); retval.stop = retval.start;

    {
        // /home/aymane/COURS/Projet antlr/s.g:73:6: ( NOM )
        // /home/aymane/COURS/Projet antlr/s.g:73:9: NOM
        {
             MATCHT(NOM, &FOLLOW_NOM_in_name280); 
            if  (HASEXCEPTION())
            {
                goto rulenameEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulenameEx; /* Prevent compiler warnings */
    rulenameEx: ;
    retval.stop = LT(-1);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return retval;
}
/* $ANTLR end name */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
